### PR TITLE
MIST-437 rename cfirewalld -> nfirewalld

### PR DESCRIPTION
**Pull request by mmlb**
MIST-437

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness-ansible/36)

### CODE REVIEW

**Comment by StevenIsaacs** [comment]
Review status: 0 of 10 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[roles/nfirewalld/templates/nfirewalld.service.j2, line 2 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/36#-JrcqJSD1_kxKGeanRuP)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/3b557a7a9370e3689e1ac4ae2e8ec651fdd28700/roles/nfirewalld/templates/nfirewalld.service.j2#L2)):</sup>
Cluster Aware?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/36)

**Comment by mmlb** [comment]
Review status: 0 of 10 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[roles/nfirewalld/templates/nfirewalld.service.j2, line 2 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/36#-JrcqJSD1_kxKGeanRuP)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/3b557a7a9370e3689e1ac4ae2e8ec651fdd28700/roles/nfirewalld/templates/nfirewalld.service.j2#L2)):</sup>
Yup, it is aware of other machines in the cluster, and which ones are allowed to contact the guests on this machine.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/36)

**Comment by trisk** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- roles/cfirewalld/defaults/main.yml @ r1
- roles/cfirewalld/handlers/main.yml @ r1
- roles/cfirewalld/meta/main.yml @ r1
- roles/cfirewalld/tasks/main.yml @ r1
- roles/cfirewalld/templates/cfirewalld.service.j2 @ r1
- roles/nfirewalld/defaults/main.yml @ r1
- roles/nfirewalld/handlers/main.yml @ r1
- roles/nfirewalld/meta/main.yml @ r1
- roles/nfirewalld/tasks/main.yml @ r1
- roles/nfirewalld/templates/nfirewalld.service.j2 @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/36)

**Comment by StevenIsaacs** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- roles/cfirewalld/defaults/main.yml @ r1
- roles/cfirewalld/handlers/main.yml @ r1
- roles/cfirewalld/meta/main.yml @ r1
- roles/cfirewalld/tasks/main.yml @ r1
- roles/cfirewalld/templates/cfirewalld.service.j2 @ r1
- roles/nfirewalld/defaults/main.yml @ r1
- roles/nfirewalld/handlers/main.yml @ r1
- roles/nfirewalld/meta/main.yml @ r1
- roles/nfirewalld/tasks/main.yml @ r1
- roles/nfirewalld/templates/nfirewalld.service.j2 @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/36)

**Pull request merged**
