### PR TITLE
MIST-436 Rename services

### PR DESCRIPTION
**Pull request by mmlb**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness-ansible/35)

### CODE REVIEW

**Comment by StevenIsaacs** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- lochness.yml @ r9
- roles/agent/handlers/main.yml @ r5
- roles/agent/tasks/main.yml @ r5
- roles/agent/templates/heartbeat.service.j2 @ r5
- roles/cherufe/defaults/main.yml @ r1
- roles/cherufe/handlers/main.yml @ r1
- roles/cherufe/tasks/main.yml @ r1
- roles/cherufe/templates/cherufe.service.j2 @ r1
- roles/dhcpd/meta/main.yml @ r7
- roles/dobharchu/defaults/main.yml @ r7
- roles/dobharchu/handlers/main.yml @ r7
- roles/dobharchu/tasks/disable.yml @ r7
- roles/dobharchu/tasks/enable.yml @ r7
- roles/dobharchu/templates/dobharchu.service.j2 @ r7
- roles/dobharchu/vars/main.yml @ r7
- roles/dover/defaults/main.yml @ r2
- roles/dover/files/dover.service @ r2
- roles/dover/handlers/main.yml @ r2
- roles/dover/tasks/disable.yml @ r2
- roles/dover/tasks/enable.yml @ r2
- roles/dover/tasks/main.yml @ r2
- roles/enfield/defaults/main.yml @ r9
- roles/enfield/handlers/main.yml @ r9
- roles/enfield/tasks/enable.yml @ r9
- roles/enfield/tasks/main.yml @ r9
- roles/enfield/templates/enfield-announce.service.j2 @ r9
- roles/enfield/templates/enfield.service.j2 @ r9
- roles/enfield/vars/main.yml @ r9
- roles/grootslang/defaults/main.yml @ r3
- roles/grootslang/files/grootslang.service @ r3
- roles/grootslang/handlers/main.yml @ r3
- roles/grootslang/tasks/disable.yml @ r3
- roles/grootslang/tasks/enable.yml @ r3
- roles/grootslang/tasks/main.yml @ r3
- roles/grootslang/templates/grootslang-announce.service.j2 @ r3
- roles/kappa/defaults/main.yml @ r4
- roles/kappa/files/kappa.service @ r4
- roles/kappa/handlers/main.yml @ r4
- roles/kappa/tasks/main.yml @ r4
- roles/kappa/templates/config.json.j2 @ r9
- roles/loveland/defaults/main.yml @ r8
- roles/loveland/files/loveland.service @ r8
- roles/loveland/handlers/main.yml @ r8
- roles/loveland/tasks/disable.yml @ r8
- roles/loveland/tasks/enable.yml @ r8
- roles/loveland/tasks/main.yml @ r8
- roles/waheela/defaults/main.yml @ r6
- roles/waheela/files/waheela.service @ r6
- roles/waheela/handlers/main.yml @ r6
- roles/waheela/tasks/disable.yml @ r6
- roles/waheela/tasks/enable.yml @ r6
- roles/waheela/tasks/main.yml @ r6
- roles/waheela/templates/waheela-announce.service.j2 @ r6
- run @ r9

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/35)

**Comment by mmlb** [comment]
damn, forgot to apply directory renames here :(

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/35)

**Comment by TauZero** [comment]
Review status: 123 of 125 files reviewed, 2 unresolved discussions, some commit checks failed.
Reviewed files:
- lochness.yml @ r9
- roles/agent/handlers/main.yml @ r5
- roles/agent/tasks/main.yml @ r5
- roles/agent/templates/heartbeat.service.j2 @ r10
- roles/agent/templates/nheartbeatd.service.j2 @ r10
- roles/cbootstrapd/defaults/main.yml @ r10
- roles/cbootstrapd/handlers/main.yml @ r10
- roles/cbootstrapd/meta/main.yml @ r10
- roles/cbootstrapd/README.md @ r10
- roles/cbootstrapd/tasks/enable.yml @ r10
- roles/cbootstrapd/tasks/main.yml @ r10
- roles/cbootstrapd/templates/cbootstrapd-announce.service.j2 @ r10
- roles/cbootstrapd/vars/main.yml @ r10
- roles/cdhcpd/defaults/main.yml @ r10
- roles/cdhcpd/handlers/main.yml @ r10
- roles/cdhcpd/meta/main.yml @ r10
- roles/cdhcpd/README.md @ r10
- roles/cdhcpd/tasks/disable.yml @ r10
- roles/cdhcpd/tasks/enable.yml @ r10
- roles/cdhcpd/tasks/main.yml @ r10
- roles/cdhcpd/templates/cdhcpd.service.j2 @ r10
- roles/cdhcpd/vars/main.yml @ r10
- roles/cfirewalld/defaults/main.yml @ r10
- roles/cfirewalld/handlers/main.yml @ r10
- roles/cfirewalld/meta/main.yml @ r10
- roles/cfirewalld/tasks/main.yml @ r10
- roles/cguestd/defaults/main.yml @ r10
- roles/cguestd/files/cguestd.service @ r10
- roles/cguestd/handlers/main.yml @ r10
- roles/cguestd/meta/main.yml @ r10
- roles/cguestd/tasks/disable.yml @ r10
- roles/cguestd/tasks/enable.yml @ r10
- roles/cguestd/tasks/main.yml @ r10
- roles/cguestd/templates/cguestd-announce.service.j2 @ r10
- roles/cherufe/defaults/main.yml @ r10
- roles/cherufe/handlers/main.yml @ r10
- roles/cherufe/meta/main.yml @ r10
- roles/cherufe/tasks/main.yml @ r10
- roles/cherufe/templates/cherufe.service.j2 @ r10
- roles/chypervisord/defaults/main.yml @ r10
- roles/chypervisord/files/chypervisord.service @ r10
- roles/chypervisord/handlers/main.yml @ r10
- roles/chypervisord/meta/main.yml @ r10
- roles/chypervisord/tasks/disable.yml @ r10
- roles/chypervisord/tasks/enable.yml @ r10
- roles/chypervisord/tasks/main.yml @ r10
- roles/chypervisord/templates/chypervisord-announce.service.j2 @ r10
- roles/cplacerd/defaults/main.yml @ r10
- roles/cplacerd/files/cplacerd.service @ r10
- roles/cplacerd/handlers/main.yml @ r10
- roles/cplacerd/meta/main.yml @ r10
- roles/cplacerd/tasks/disable.yml @ r10
- roles/cplacerd/tasks/enable.yml @ r10
- roles/cplacerd/tasks/main.yml @ r10
- roles/cworkerd/defaults/main.yml @ r10
- roles/cworkerd/files/cworkerd.service @ r10
- roles/cworkerd/handlers/main.yml @ r10
- roles/cworkerd/meta/main.yml @ r10
- roles/cworkerd/tasks/disable.yml @ r10
- roles/cworkerd/tasks/enable.yml @ r10
- roles/cworkerd/tasks/main.yml @ r10
- roles/dhcpd/meta/main.yml @ r7
- roles/dobharchu/defaults/main.yml @ r10
- roles/dobharchu/handlers/main.yml @ r10
- roles/dobharchu/meta/main.yml @ r10
- roles/dobharchu/README.md @ r10
- roles/dobharchu/tasks/disable.yml @ r10
- roles/dobharchu/tasks/enable.yml @ r10
- roles/dobharchu/tasks/main.yml @ r10
- roles/dobharchu/templates/dobharchu.service.j2 @ r10
- roles/dobharchu/vars/main.yml @ r10
- roles/dover/defaults/main.yml @ r10
- roles/dover/files/dover.service @ r10
- roles/dover/handlers/main.yml @ r10
- roles/dover/meta/main.yml @ r10
- roles/dover/tasks/disable.yml @ r10
- roles/dover/tasks/enable.yml @ r10
- roles/dover/tasks/main.yml @ r10
- roles/enfield/defaults/main.yml @ r10
- roles/enfield/handlers/main.yml @ r10
- roles/enfield/meta/main.yml @ r10
- roles/enfield/README.md @ r10
- roles/enfield/tasks/enable.yml @ r10
- roles/enfield/tasks/main.yml @ r10
- roles/enfield/templates/enfield-announce.service.j2 @ r10
- roles/enfield/templates/enfield.service.j2 @ r10
- roles/enfield/vars/main.yml @ r10
- roles/grootslang/defaults/main.yml @ r10
- roles/grootslang/files/grootslang.service @ r10
- roles/grootslang/handlers/main.yml @ r10
- roles/grootslang/meta/main.yml @ r10
- roles/grootslang/tasks/disable.yml @ r10
- roles/grootslang/tasks/enable.yml @ r10
- roles/grootslang/tasks/main.yml @ r10
- roles/grootslang/templates/grootslang-announce.service.j2 @ r10
- roles/kappa/defaults/main.yml @ r10
- roles/kappa/files/kappa.service @ r10
- roles/kappa/handlers/main.yml @ r10
- roles/kappa/meta/main.yml @ r10
- roles/kappa/tasks/main.yml @ r10
- roles/kappa/templates/config.json.j2 @ r10
- roles/loveland/defaults/main.yml @ r10
- roles/loveland/files/loveland.service @ r10
- roles/loveland/handlers/main.yml @ r10
- roles/loveland/meta/main.yml @ r10
- roles/loveland/tasks/disable.yml @ r10
- roles/loveland/tasks/enable.yml @ r10
- roles/loveland/tasks/main.yml @ r10
- roles/nconfigd/defaults/main.yml @ r10
- roles/nconfigd/files/nconfigd.service @ r10
- roles/nconfigd/handlers/main.yml @ r10
- roles/nconfigd/meta/main.yml @ r10
- roles/nconfigd/tasks/main.yml @ r10
- roles/nconfigd/templates/config.json.j2 @ r12
- roles/waheela/defaults/main.yml @ r10
- roles/waheela/files/waheela.service @ r10
- roles/waheela/handlers/main.yml @ r10
- roles/waheela/meta/main.yml @ r10
- roles/waheela/tasks/disable.yml @ r10
- roles/waheela/tasks/enable.yml @ r10
- roles/waheela/tasks/main.yml @ r10
- roles/waheela/templates/waheela-announce.service.j2 @ r10
- run @ r11

---

<sup>**[roles/cbootstrapd/templates/cbootstrapd.service.j2, line 2 \[r12\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/35#-JqkKcr6eNJg5ObULnrI)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/854a94985a3b0bd675677872ab7ed42b2425e353/roles/cbootstrapd/templates/cbootstrapd.service.j2#L2)):</sup>
Not Enfield anymore

---

<sup>**[roles/cfirewalld/templates/cfirewalld.service.j2, line 2 \[r12\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/35#-JqkJL0j_LozbpDqPFny)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/854a94985a3b0bd675677872ab7ed42b2425e353/roles/cfirewalld/templates/cfirewalld.service.j2#L2)):</sup>
Not Cherufe anymore

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/35)

**Comment by mmlb** [comment]
Review status: 122 of 125 files reviewed, 2 unresolved discussions, some commit checks failed.

---

<sup>**[roles/cbootstrapd/templates/cbootstrapd.service.j2, line 2 \[r12\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/35#-JqkKcr6eNJg5ObULnrI)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/854a94985a3b0bd675677872ab7ed42b2425e353/roles/cbootstrapd/templates/cbootstrapd.service.j2#L2)):</sup>
ahh a case of wrong case :smile: 
Done

---

<sup>**[roles/cfirewalld/templates/cfirewalld.service.j2, line 2 \[r12\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/35#-JqkJL0j_LozbpDqPFny)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/854a94985a3b0bd675677872ab7ed42b2425e353/roles/cfirewalld/templates/cfirewalld.service.j2#L2)):</sup>
same deal
Done

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/35)

**Comment by TauZero** [comment]
Review status: 124 of 125 files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- roles/cbootstrapd/templates/cbootstrapd.service.j2 @ r13
- roles/cfirewalld/templates/cfirewalld.service.j2 @ r13

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/35)

**Comment by TauZero** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- lochness.yml @ r14
- roles/nconfigd/files/nconfigd.service @ r13
- roles/nconfigd/templates/config.json.j2 @ r14
- run @ r14

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/35)

**Pull request merged**
