### PR TITLE
Mist-453 Image Service Role

### PR DESCRIPTION
**Pull request by TauZero**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness-ansible/34)

### CODE REVIEW

**Comment by mmlb** [comment]
Review status: 0 of 12 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[roles/kappa/templates/config.json.j2, line 14 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/34#-JqWKWxO-ya1kFdp0FV0)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/a8a184b3e85c8cae1e743c9f3c4a452b79a2856f/roles/kappa/templates/config.json.j2#L14)):</sup>
put after grootslang to stick with alphabetical order

---

<sup>**[run, line 96 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/34#-JqWKcNcpzXRKeX7OK3W)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/a8a184b3e85c8cae1e743c9f3c4a452b79a2856f/run#L96)):</sup>
ditto

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/34)

**Comment by mmlb** [comment]
Review status: 10 of 12 files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- lochness.yml @ r1
- roles/image/defaults/main.yml @ r1
- roles/image/files/mistify-image-service.service @ r1
- roles/image/handlers/main.yml @ r1
- roles/image/meta/main.yml @ r1
- roles/image/README.md @ r1
- roles/image/tasks/disable.yml @ r1
- roles/image/tasks/enable.yml @ r1
- roles/image/tasks/main.yml @ r1
- roles/image/templates/mistify-image-service-announce.service.j2 @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/34)

**Comment by TauZero** [comment]
Review status: 10 of 12 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[roles/kappa/templates/config.json.j2, line 14 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/34#-JqWKWxO-ya1kFdp0FV0)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/a8a184b3e85c8cae1e743c9f3c4a452b79a2856f/roles/kappa/templates/config.json.j2#L14)):</sup>
Done.

---

<sup>**[run, line 96 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/34#-JqWKcNcpzXRKeX7OK3W)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/a8a184b3e85c8cae1e743c9f3c4a452b79a2856f/run#L96)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/34)

**Comment by mmlb** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- roles/kappa/templates/config.json.j2 @ r2
- run @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/34)

**Pull request merged**
