### PR TITLE
MIST-505 Add mistify-ovs-subagent

### PR DESCRIPTION
**Pull request by TauZero**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness-ansible/40)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[roles/agent/templates/mistify-agent-ovs.service.j2, line 3 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/40#-JuwBimSLlwVHALJ4B5G)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/75c2a332ef487f3f54d0d7095cb78084919df84e/roles/agent/templates/mistify-agent-ovs.service.j2#L3)):</sup>
This should have a `Requires=openvswitcher.service` also would negate need to have it in `main.yml`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/40)

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[roles/agent/templates/mistify-agent-ovs.service.j2, line 3 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/40#-JuwBimSLlwVHALJ4B5G)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/75c2a332ef487f3f54d0d7095cb78084919df84e/roles/agent/templates/mistify-agent-ovs.service.j2#L3)):</sup>
I modeled it after the docker subagent stuff, which requres docker in main.yml. Fixed here (left docker sub alone)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/40)

**Comment by mmlb** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[roles/agent/templates/mistify-agent-ovs.service.j2, line 3 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/40#-JuwBimSLlwVHALJ4B5G)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/75c2a332ef487f3f54d0d7095cb78084919df84e/roles/agent/templates/mistify-agent-ovs.service.j2#L3)):</sup>
hmm maybe openvswitch task should stay with at least `enabled=yes`, let me check.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/40)

**Comment by mmlb** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[roles/agent/templates/mistify-agent-ovs.service.j2, line 3 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/40#-JuwBimSLlwVHALJ4B5G)** ([raw file](https://github.com/mistifyio/lochness-ansible/blob/75c2a332ef487f3f54d0d7095cb78084919df84e/roles/agent/templates/mistify-agent-ovs.service.j2#L3)):</sup>
Nope, not needed. systemd will see that openvswitch is required by mistify-agent-ovs which is enabled and will be sure to start openvswitch.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/40)

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/40)

**Pull request merged**
