### PR TITLE
MIST-465 dnsmasq and other tweaks

### PR DESCRIPTION
**Pull request by mmlb**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness-ansible/37)

### CODE REVIEW

**Comment by TauZero** [comment]
Reviewed 2 of 2 files at r1, 12 of 28 files at r2, 4 of 5 files at r3, 13 of 13 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/37)

**Comment by trisk** [comment]
Reviewed 2 of 2 files at r1, 12 of 28 files at r2, 4 of 5 files at r3, 13 of 13 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/37)

**Comment by daleghent** [comment]
Reviewed 2 of 2 files at r1, 12 of 28 files at r2, 4 of 5 files at r3, 13 of 13 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/37)

**Comment by StevenIsaacs** [comment]
Reviewed 2 of 2 files at r1, 3 of 28 files at r2, 4 of 5 files at r3, 2 of 13 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness-ansible/37)

**Pull request merged**
